version: '3.8'

services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
    ports:
      - '${DB_PORT}:${DB_PORT}'
  app:
    container_name: app
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - '${API_PORT}:${API_PORT}'
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - DB_HOST=db
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
